shell=/usr/bin/sh -c "tmux"
# font=JetBrainsMono Nerd Font:size=11
font=0xProto Nerd Font Mono:size=11
include=/usr/share/foot/themes/selenized-black
[desktop-notifications]
command=notify-send -a ${app-id} -i ${app-id} ${title} ${body}command=notify-send -a ${app-id} -i ${app-id} ${title} ${body}command=notify-send -a ${app-id} -i ${app-id} ${title} ${body}command=notify-send -a ${app-id} -i ${app-id} ${title} ${body}
[scrollback]
lines=100000
[cursor]
style=block
