theme = "everforest_dark"

[editor.statusline]
right = ["diagnostics", "selections", "position", "position-percentage"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor]
line-number = "absolute"
mouse = true
color-modes = true
default-yank-register = "+"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

